spring.application.name=task
spring.application.description=Task Scheduler - Task module

server.forward-headers-strategy = framework
server.port=8081

ts.scheduler.frequency=${TS_TASK_NOTIFICATION_TRIGGER_FREQUENCY}

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

spring.data.mongodb.uri=mongodb://${TS_MONGO_USER}:${TS_MONGO_PASSWORD}@${TS_MONGO_HOST}:${TS_MONGO_PORT}?authSource=admin
spring.data.mongodb.database=${TS_MONGO_DB}
spring.data.mongodb.uuid-representation=standard

spring.rabbitmq.host=${TS_RABBITMQ_HOST}
spring.rabbitmq.port=${TS_RABBITMQ_PORT}
spring.rabbitmq.username=${TS_RABBITMQ_TASK_USER}
spring.rabbitmq.password=${TS_RABBITMQ_TASK_PASSWORD}
spring.rabbitmq.virtual-host=${TS_RABBITMQ_VHOST}